version: '3.4'

services:

  traefik:
    image: traefik:v2.11
    container_name: traefik
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - "rabbitmq"
      - "orchestrationlab.api"

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.12.10-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '1GB'
          
  orchestrationlab.api:
    image: ${DOCKER_REGISTRY-}orchestrationlabapi
    build:
      context: ../../src/Presentation
      dockerfile: OrchestrationLab.Api/Dockerfile
    ports:
      - 5103:8080
      - 7045:8081
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '1GB'
    depends_on:
      - "rabbitmq"