http:
  routers:
    traefik:
      rule: "Host(`traefik.orchestrationlab.localhost`)"
      service: "api@internal"
    
    rabbitmq:
      rule: "Host(`rabbitmq.orchestrationlab.localhost`)"
      service: "rabbitmq"

    orchestrationlab.api:
      rule: "Host(`public-api.orchestrationlab.localhost`)"
      service: "orchestrationlab.api"

  services:
    rabbitmq:
      loadbalancer:
        servers:
          - url: "http://host.docker.internal:15672"
    orchestrationlab.api:
      loadbalancer:
        servers:
          - url: "http://host.docker.internal:5103"