global:
  sendAnonymousUsage: false
  checkNewVersion: true

api:
  dashboard: true
  insecure: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: DEBUG
  format: common


entryPoints:
  http:
    address: ":80"